mod error;
mod lookup;

/// Private re-exports used by macro-generated code. Not part of the public API.
#[doc(hidden)]
pub mod __private {
    pub use retour::StaticDetour;
    pub use std::sync::Mutex;
}
/// Macro used to hook multiple `retour::StaticDetour`s at once
///
/// Reads a `mod` block and generating static detours from #[hook] macros.
/// #[hook] is not its own macro that gets expanded, it is read and removed by the [`hook_module`]
///
/// # `#[hook] syntax
/// Hook based off symbol
/// ```ignore
/// #[hook(<unsafe> <extern> <ABI> DETOUR_NAME, symbol = "SYMBOL_NAME")]
/// ```
/// Hook based off offset
/// ```ignore
/// #[hook(<unsafe> <extern> <ABI> DETOUR_NAME, offset = 0xDEAD_BEEF)]
/// ```
/// Examples:
/// ```ignore
/// #[hook(unsafe extern "system" MessageBoxA_Detour, symbol = "MessageBoxA")]
/// fn messageboxw_detour(hwnd: HWND, text: PCWSTR, _caption: PCWSTR, u_type: u32) -> i32 { ... }
///
/// #[hook(Add_Detour, symbol = "add")]
/// fn add(a: i32, b: i32) -> i32 { ... }
///
/// #[hook(lua_newstate_Detour, offset = 0x4321)]
/// fn add(a: i32, b: i32) -> i32 { ... }
/// ```
///
///
/// # Example
/// ```ignore
/// use retour_utils::hook_module;
///
/// #[hook_module("lua52.dll")]
/// mod lua {
///     // Creates a StaticDetour called Lua_newstate with the same function type as our function
///     // (minus abi/unsafe to work with retour crate)
///     #[hook(unsafe extern "C" Lua_newstate, symbol = "Lua_newstate")]
///     pub fn newstate(f: *mut lua_Alloc, ud: *mut std::ffi::c_void) -> *mut lua_State {
///         unsafe {
///             Lua_newstate.call(f, ud)
///         }
///     }
///
///     // == Generated by macro: ==
///     // #[hook_module] will create `MODULE_NAME`:
///     const MODULE_NAME: &str = "lua52.dll"
///     // and init_detours function
///     pub unsafe init_detours() -> crate::Result<()> {..}
///     // which will initialize all the StaticDetours generated by the macro inside this module
/// }
/// ```
pub use retour_utils_impl::hook_impl;
pub use retour_utils_impl::hook_module;


pub use error::Error;
pub use lookup::*;

use minidl::Library;
use std::path::Path;

type Result<T> = std::result::Result<T, Error>;

/// Initialize detour by passing the address of original function to `init_detour_fn`
///
/// This is called by `init_detours`, which is generated by the [`hook_module`] macro
pub fn init_detour(
    lookup_data: LookupData,
    init_detour_fn: impl Fn(*const ()) -> retour::Result<()>,
) -> Result<()> {
    let handle = match lookup_data.get_module() {
        Some(name) => Library::load(Path::new(name)).map_err(|e| Error::IoError(e))?,
        None => load_self()?,
    };
    let Some(addr) = lookup_data.address_from_handle(&handle) else {
        return Err(Error::SymbolNotFound);
    };
    init_detour_fn(addr)?;

    Ok(())
}

/// Open a handle to the current process/executable (the "self" module).
fn load_self() -> Result<Library> {
    #[cfg(unix)]
    {
        use std::os::raw::c_int;
        unsafe extern "C" {
            fn dlopen(filename: *const std::os::raw::c_char, flags: c_int)
            -> *mut std::ffi::c_void;
        }
        const RTLD_LAZY: c_int = 1;
        let handle = unsafe { dlopen(std::ptr::null(), RTLD_LAZY) };
        unsafe { Library::from_ptr(handle) }
            .ok_or_else(|| Error::IoError(std::io::Error::last_os_error()))
    }
    #[cfg(windows)]
    {
        unsafe extern "system" {
            fn GetModuleHandleW(lpModuleName: *const u16) -> *mut std::ffi::c_void;
        }
        let handle = unsafe { GetModuleHandleW(std::ptr::null()) };
        unsafe { Library::from_ptr(handle) }
            .ok_or_else(|| Error::IoError(std::io::Error::last_os_error()))
    }
    #[cfg(not(any(unix, windows)))]
    {
        Err(Error::ModuleNotLoaded)
    }
}
